import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Promt = localFont({
  src: "/font/Prompt-Regular.ttf",
  variable: "--font-custom",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Promt.variable} antialiased`}>{children}</body>
    </html>
  );
}
